"""add unique constraints to child tables

Revision ID: e4bc992b21e8
Revises: 306262f13a15
Create Date: 2025-09-08 12:19:56.004990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4bc992b21e8'
down_revision: Union[str, None] = '306262f13a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_conditions_natural_key', 'conditions', ['nct_id', 'name'])
    op.create_unique_constraint('uq_design_outcomes_natural_key', 'design_outcomes', ['nct_id', 'outcome_type', 'measure'])
    op.create_unique_constraint('uq_interventions_natural_key', 'interventions', ['nct_id', 'intervention_type', 'name'])
    op.create_unique_constraint('uq_sponsors_natural_key', 'sponsors', ['nct_id', 'name', 'agency_class'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sponsors_natural_key', 'sponsors', type_='unique')
    op.drop_constraint('uq_interventions_natural_key', 'interventions', type_='unique')
    op.drop_constraint('uq_design_outcomes_natural_key', 'design_outcomes', type_='unique')
    op.drop_constraint('uq_conditions_natural_key', 'conditions', type_='unique')
    # ### end Alembic commands ###
